### ISSUE TITLE
tests todo list

### ISSUE THREAD

**Issue by hayd** [hayd/pep8radius#25]
The new file structure is now much less of a mess (not just one file), so should be able to more trivially tick a couple of these off / be clear where to put things.
- [ ] test udiff functions (extracting line numbers and removed lines) + *.
- [ ] test diff output
- [x] test ~~dry-run~~ in-place (idea: just do a dry run in check as first thing, or alternatively do a little for loop of different configurations of diff and dry-run and ... ?)
- [ ] example tests with * (update/note to self: wtf is *?)
- [ ] tests for more edge cases in autopep8 line range (off topic if already in their tests?)
- [x] excludes and other options (?) _not_ passed on to autopep8
- [x] version number
- [x] list-fixes
- [x] bad rev
- [ ] specific rev (idea: perhaps `successfully_commit...` could return commit hash)
- [ ] test against branches ~~(not convinced there is a need to do this, as git/hg diff is doing the work here, but should confirm this ? :S )~~ specifically bazaar (I skip a test atm)
- [ ] test with bad syntax
- [x] bad vc (passed to new)
- [x] ~~no vc in directory (`which_version_control` raises)~~  ... no cover ;)
- [x] be able to run tests (safely) without being in test directory #27
- [x] Potentially delete .git and .hg on tearDown (seems kindof wasteful to do this for each test, would prefer if could do on just the init setup and final tearDown?).

\* udiffs with lines combined and distinct lines in multiple files.
